# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapReduce.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapReduce.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"\x17\n\x06status\x12\r\n\x05state\x18\x01 \x01(\t\"1\n\x08Identity\x12\x12\n\nreducer_id\x18\x01 \x01(\x05\x12\x11\n\tmapper_id\x18\x02 \x01(\x05\"}\n\x07mapData\x12\x10\n\x08startIdx\x18\x01 \x01(\x05\x12\x0e\n\x06\x65ndIdx\x18\x02 \x01(\x05\x12\x10\n\x08iter_num\x18\x03 \x01(\x05\x12\x10\n\x08reducers\x18\x04 \x01(\x05\x12\x11\n\tmapper_id\x18\x05 \x01(\x05\x12\x19\n\tcentroids\x18\x06 \x03(\x0b\x32\x06.Point\"_\n\nreduceData\x12\x10\n\x08iter_num\x18\x01 \x01(\x05\x12\x15\n\rmy_reducer_id\x18\x02 \x01(\x05\x12\x17\n\x0fwork_reducer_id\x18\x03 \x01(\x05\x12\x0f\n\x07mappers\x18\x04 \x01(\x05\"2\n\x04Pair\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x01(\x02\x12\x15\n\x05point\x18\x02 \x01(\x0b\x32\x06.Point\"\x1d\n\x05Pairs\x12\x14\n\x05pairs\x18\x01 \x03(\x0b\x32\x05.Pair\"1\n\nReduceResp\x12\x14\n\x05pairs\x18\x01 \x03(\x0b\x32\x05.Pair\x12\r\n\x05state\x18\x02 \x01(\t24\n\x0fMasterAndMapper\x12!\n\nmapRequest\x12\x08.mapData\x1a\x07.status\"\x00\x32?\n\x10MasterAndReducer\x12+\n\rreduceRequest\x12\x0b.reduceData\x1a\x0b.ReduceResp\"\x00\x32\x33\n\x10MapperAndReducer\x12\x1f\n\x08getPairs\x12\t.Identity\x1a\x06.Pairs\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapReduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=19
  _globals['_POINT']._serialized_end=48
  _globals['_STATUS']._serialized_start=50
  _globals['_STATUS']._serialized_end=73
  _globals['_IDENTITY']._serialized_start=75
  _globals['_IDENTITY']._serialized_end=124
  _globals['_MAPDATA']._serialized_start=126
  _globals['_MAPDATA']._serialized_end=251
  _globals['_REDUCEDATA']._serialized_start=253
  _globals['_REDUCEDATA']._serialized_end=348
  _globals['_PAIR']._serialized_start=350
  _globals['_PAIR']._serialized_end=400
  _globals['_PAIRS']._serialized_start=402
  _globals['_PAIRS']._serialized_end=431
  _globals['_REDUCERESP']._serialized_start=433
  _globals['_REDUCERESP']._serialized_end=482
  _globals['_MASTERANDMAPPER']._serialized_start=484
  _globals['_MASTERANDMAPPER']._serialized_end=536
  _globals['_MASTERANDREDUCER']._serialized_start=538
  _globals['_MASTERANDREDUCER']._serialized_end=601
  _globals['_MAPPERANDREDUCER']._serialized_start=603
  _globals['_MAPPERANDREDUCER']._serialized_end=654
# @@protoc_insertion_point(module_scope)
